### ISSUE TITLE
PEMFC P2D Model

### ISSUE THREAD

**Issue by decaluwe** [coresresearch/coresresearch#15]
Finish PEMFC Model

- [x] Update p2d_pemfc README
- [x] Clean up code and push to Github
- [x] Verify Flooded Agglomerate radial terms
- [x] Develop fitting routines (using `scikit-learn`?)
- [x] Add in tracking for surface sites - multi rxns
- [x] Check Butler Volmer in Cantera
- [x] Check kinetic parameters against literature

**Comment by c-randall** [comment]
Closing out old things assigned to me so I can cleanup my GitHub profile/notifications.
