### ISSUE TITLE
Carbon-Nafion NR paper

### ISSUE THREAD

**Issue by decaluwe** [coresresearch/coresresearch#7]
Data analysis:
 - [x] GO_Sample1
 - [x] GO_Sample2
 - [x] C60_ORNL

ACNS presentation:
 - [x] powerpoint
 - [x] practice

Paper:
 - [x] introduction
 - [x] experiments
 - [x] results
 - [x] discussion
 - [x] conclusion
 - [x] review
 - [x] submit

**Comment by c-randall** [comment]
Closing out old things assigned to me so I can cleanup my GitHub profile/notifications.
